# Generated by Django 5.1.3 on 2024-11-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Пароль")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото пользователя",
                        null=True,
                        upload_to="users/",
                        verbose_name="Фото",
                    ),
                ),
                ("token", models.CharField(max_length=100, verbose_name="Токен")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
