# Generated by Django 5.1.3 on 2024-11-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_mailing_frequency_alter_mailing_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="interval",
        ),
    ]
