# Generated by Django 5.1.3 on 2024-11-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_remove_mailing_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("day", "ежедневно"),
                    ("week", "еженедельно"),
                    ("month", "ежемесячно"),
                ],
                max_length=10,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
