# Generated by Django 5.1.3 on 2024-11-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_alter_mailing_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_first_mailing",
            field=models.DateTimeField(verbose_name="Дата рассылки"),
        ),
    ]
