# Generated by Django 5.1.3 on 2024-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_alter_mailing_datetime_first_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_first_mailing",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата рассылки"),
        ),
    ]
