# Generated by Django 5.1.3 on 2024-11-19 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0008_alter_mailing_datetime_first_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="datetime_first_mailing",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата рассылки"
            ),
        ),
    ]
