# Generated by Django 5.1.3 on 2024-11-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0009_alter_mailing_datetime_first_mailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="date_time_last_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последней рассылки"
            ),
        ),
    ]
