# Generated by Django 5.1.3 on 2024-11-19 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0010_mailing_date_time_last_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_time_last_mailing",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Дата последней рассылки",
            ),
        ),
    ]
