# Generated by Django 5.1.3 on 2024-11-19 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0011_alter_mailing_date_time_last_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_time_last_mailing",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Последний день рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="datetime_first_mailing",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Содержание сообщения"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Тема сообщения"),
        ),
    ]
