# Generated by Django 5.1.3 on 2024-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0014_alter_client_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "ежедневно"),
                    ("week", "еженедельно"),
                    ("month", "ежемесячно"),
                ],
                max_length=10,
                null=True,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
