# Generated by Django 5.0.7 on 2024-11-28 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="views_count",
            new_name="views",
        ),
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
